package hibernate_oefening;
// Generated 3-dec-2014 14:35:30 by Hibernate Tools 3.6.0



/**
 * TbiLokaal generated by hbm2java
 */
public class TbiLokaal  implements java.io.Serializable {


     private Integer id;
     private String lokaalnaam;
     private int aantalPlaatsen;

    public TbiLokaal() {
    }

    public TbiLokaal(String lokaalnaam, int aantalPlaatsen) {
       this.lokaalnaam = lokaalnaam;
       this.aantalPlaatsen = aantalPlaatsen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLokaalnaam() {
        return this.lokaalnaam;
    }
    
    public void setLokaalnaam(String lokaalnaam) {
        this.lokaalnaam = lokaalnaam;
    }
    public int getAantalPlaatsen() {
        return this.aantalPlaatsen;
    }
    
    public void setAantalPlaatsen(int aantalPlaatsen) {
        this.aantalPlaatsen = aantalPlaatsen;
    }




}


