package hibernate_oefening;
// Generated 3-dec-2014 14:35:30 by Hibernate Tools 3.6.0



/**
 * TblCursist generated by hbm2java
 */
public class TblCursist  implements java.io.Serializable {


     private Integer id;
     private String voornaam;
     private String familienaam;
     private String email;
     private String gsm;

    public TblCursist() {
    }

    public TblCursist(String voornaam, String familienaam, String email, String gsm) {
       this.voornaam = voornaam;
       this.familienaam = familienaam;
       this.email = email;
       this.gsm = gsm;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getFamilienaam() {
        return this.familienaam;
    }
    
    public void setFamilienaam(String familienaam) {
        this.familienaam = familienaam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGsm() {
        return this.gsm;
    }
    
    public void setGsm(String gsm) {
        this.gsm = gsm;
    }




}


