package hibernate_oefening;
// Generated 3-dec-2014 14:35:30 by Hibernate Tools 3.6.0



/**
 * TblModule generated by hbm2java
 */
public class TblModule  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private int docentId;
     private int lokaalId;

    public TblModule() {
    }

    public TblModule(String naam, int docentId, int lokaalId) {
       this.naam = naam;
       this.docentId = docentId;
       this.lokaalId = lokaalId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public int getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(int docentId) {
        this.docentId = docentId;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }




}


